.TH SG_LOGS "8" "October 2004" "sg3_utils-1.09" SG3_UTILS
.SH NAME
sg_logs \- read SCSI device log pages and some log modifications
.SH SYNOPSIS
.B sg_logs
[\fI-a\fR] [\fI-c=<page_control>\fR] [\fI-h\fR] [\fI-l\fR]
[\fI-p=<page_code>\fR] [\fI-paramp=<parameter_pointer>\fR] [\fI-pcb\fR]
[\fI-ppc\fR] [\fI-r\fR] [\fI-sp\fR] [\fI-t\fR] [\fI-v\fR] [\fI-V\fR]
[\fI-?\fR] \fI<scsi_device>\fR
.SH DESCRIPTION
.\" Add any additional description here
.PP
This utility sends a LOG SENSE SCSI command to the given device and then
outputs the response. This is used in most cases to fetch log pages
stored on the given device and known log pages are decoded and output
in ASCII. In one case a LOG SELECT SCSI command is issued to reset
parameters back to the device manufacturer's default values.
this utility.
.TP
-a
outputs all the log pages supported by the device.
.TP
-c=page_control
accepts 0, 1, 2 or 3 as an argument. 0 for current threshhold values,
1 for current cumulative values, 2 for default threshhold values and 3
for default cumulative values. The default is 1 (i.e. current threshhold
values).
.TP
-h
suppresses decoding of known log sense pages and prints out the
response in hex instead.
.TP
-l
lists the names of all logs sense pages supported by this device.
See the list of common log page codes below.
.TP
-p=<page_code>
log page code to fetch. Should be a hexadecimal number between 0 and 3f
inclusive.
.TP
-paramp=<parameter_pointer>
parameter pointer value (in hex) to place in command. Should be a number
between 0 and ffff inclusive. 
.TP
-pcb
show Parameter Control Byte settings (only relevant when log parameters
being output in ASCII).
.TP
-ppc
sets the Parameter Pointer Control (PPC) bit. Default is 0 (i.e. cleared).
.TP
-r
use LOG SELECT SCSI command to reset all implemented parameter values
to be the device defined (i.e. manufacturer's) default values. In most
cases the default values are zeroes. This option seems to
clear error counter log pages but leaves pages like self-test results,
start-stop cycle counter and temperature log pages uneffected.
This option may be required to clear log pages if a counter reaches its
maximum value since the log page in which the counter is found will
remain "stuck" until something is done.
.TP
-sp
sets the Saving Parameters (SP) bit. Default is 0 (i.e. cleared).
.TP
-t
outputs the temperature. First looks in the temperature log page and if
that is not available tries the Informational Exceptions page which may also
have the current temperature (especially in older disks).
.TP
-v
verbose: show SCSI command blocks prior to execution.
.TP
-V
print out version string
.TP
-?
output usage message. Ignore all other parameters.
.PP
Various log pages hold information error rates, device temperature,
start stop cycles since device produced and the results of the last
20 self tests. Self tests can be initiated by the sg_senddiag utility.
The smartmontools package provides much of the information found with
sg_logs in a form suitable for monitoring the health of SCSI disks and
tape drives.
.PP
Here is a list of commonly used log pages (drop the "0x" prefix when
using them as an argument to the '-p=' option):
.PP
0x0     Supported log pages
.br
0x2     Write error counter
.br
0x3     Read error counter
.br
0x6     Non-medium error
.br
0x7     Last n error events
.br
0xd     Temperature
.br
0xe     Start-stop cycle counter
.br
0x10    Self-test results
.br
0x18    Protocol specific port
.br
0x2f    Informational exceptions
.PP
In the 2.4 series of Linux kernels the given device must be
a SCSI generic (sg) device. In the 2.6 series block devices (e.g. disks
and SCSI DVDs) can also be specified. For example "sg_logs -a /dev/sda"
will work in the 2.6 series kernels.
.SH AUTHOR
Written by Doug Gilbert
.SH "REPORTING BUGS"
Report bugs to <dgilbert at interlog dot com>.
.SH COPYRIGHT
Copyright \(co 2002-2004 Douglas Gilbert
.br
This software is distributed under the GPL version 2. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.B smartctl(smartmontools: see net), sg_senddiag(sg3_utils)
