.TH SG_LOGS "8" "April 2003" "sg3_utils-1.04" SG3_UTILS
.SH NAME
sg_logs \- reads SCSI LOG SENSE pages
.SH SYNOPSIS
.B sg_logs
[\fI-a\fR] [\fI-c=<page_control>\fR] [\fI-h\fR] [\fI-l\fR]
[\fI-p=<page_code>\fR] [\fI-paramp=<parameter_pointer>\fR] [\fI-ppc\fR]
[\fI-sp\fR] [\fI-t\fR] [\fI-V\fR] [\fI-?\fR] \fI<sg_device>\fR
.SH DESCRIPTION
.\" Add any additional description here
.PP
This utility sends a LOG SENSE SCSI command to the given device and then
outputs the response. There is no facility to change log page data with 
this utility.
.TP
-a
outputs all the log pages supported by the device.
.TP
-c=page_control
accepts 0, 1, 2 or 3 as an argument. 0 for current threshhold values,
1 for current cumulative values, 2 for default threshhold values and 3
for default cumulative values. The default is 1 (i.e. current threshhold
values).
.TP
-h
suppresses decoding of known log sense pages and prints out the
response in hex instead.
.TP
-l
lists the names of all logs sense pages supported by this device.
.TP
-p=<page_code>
log page code to fetch. Should be a hexadecimal number between 0 and 3f
inclusive.
.TP
-paramp=<parameter_pointer>
parameter pointer value (in hex) to place in command. Should be a number
between 0 and ffff inclusive. 
.TP
-ppc
sets the Parameter Pointer Control (PPC) bit. Default is 0 (i.e. cleared).
.TP
-sp
sets the Saving Parameters (SP) bit. Default is 0 (i.e. cleared).
.TP
-t
outputs the temperature. First looks in the temperature log page and if
that is not available tries the Informational Exceptions page which may also
have the current temperature (especially in older disks).
.TP
-V
print out version string
.TP
-?
output usage message. Ignore all other parameters.
.PP
Various log pages hold information error rates, device temperature,
start stop cycles since device produced and the results of the last
20 self tests. Self tests can be initiated by the sg_senddiag utility.
.PP
In the 2.4 series of Linux kernels the given device must be
a SCSI generic (sg) device. In the 2.5 series block devices (e.g. disks
and SCSI DVDs) can also be specified. For example "sg_logs -a /dev/sda"
will work in the 2.5 series kernels.
.SH AUTHOR
Written by Doug Gilbert
.SH "REPORTING BUGS"
Report bugs to <dgilbert@interlog.com>.
.SH COPYRIGHT
Copyright \(co 2002-2003 Douglas Gilbert
.br
This software is distributed under the GPL version 2. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.B smartmontools(see net), sg_senddiag(sg3_utils)
