.TH SG_TURS "8" "June 2006" "sg3_utils-1.21" SG3_UTILS
.SH NAME
sg_turs \- executes a user specified number of TEST UNIT READY commands on
the given device
.SH SYNOPSIS
.B sg_turs
[\fI-n=<number of commands to send>\fR] [\fI-p\fR]  [\fI-t\fR] [\fI-v\fR]
[\fI-V\fR] <\fIscsi_device\fR>
.SH DESCRIPTION
.\" Add any additional description here
.PP
sg_turs sends a number of TEST UNIT READY commands to a given SCSI
device. Useful for timing the per command overhead. Note that
TEST UNIT READY has no associated data, just a 6 byte command and a
returned SCSI status value.
.TP
-n=<num>
performs TEST UNIT READY "<num>" times. If not given defaults to 1.
These suffix multipliers are permitted: c C *1; w W *2; b B *512;
k K KiB *1,024; KB *1,000; m M MiB *1,048,576; MB *1,000,000;
g G GiB *1,073,741,824; and GB *1,000,000,000 . Also a suffix of the
form "x<n>" multiplies the leading number by <n>. Alternatively a hex
number may be given, prefixed by either '0x' or '0X' (or has a
trailing 'h' or 'H').
.TP
-p
show progress indication (a percentage) if available. If <num> greater
than one waits 30 seconds before subsequent checks. Exits when <num>
is reached or there is no more progress indication. Ignores '-t' option.
.TP
-t
after completing the requested number of TEST UNIT READY commands, outputs
the total duration and the average number of commands executed per second.
.TP
-v
increase level of verbosity: print out SCSI commands in hex prior to
sending them to the device. '-vv' and '-vvv' are also accepted yielding
greater verbosity.
.TP
-V
print out version string then exit.
.SH EXIT STATUS
The exit status of sg_verify is 0 when it is successful. Otherwise see
the sg3_utils(8) man page.
.SH AUTHORS
Written by D. Gilbert
.SH COPYRIGHT
Copyright \(co 2000-2005 Douglas Gilbert
.br
This software is distributed under the GPL version 2. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
