SHELL = /bin/sh

PREFIX=/usr/local
INSTDIR=$(DESTDIR)/$(PREFIX)/bin
MANDIR=$(DESTDIR)/$(PREFIX)/man

## CXX = g++
## CXX = clang++
## CXX = clang++-7
CXXLD = $(CXX)

EXECS = sg_tst_excl sg_tst_excl2 sg_tst_excl3 sg_tst_context sg_tst_async \
	sgh_dd

EXTRAS =

BSG_EXTRAS =


MAN_PGS = 
MAN_PREF = man8

LARGE_FILE_FLAGS = -D_LARGEFILE64_SOURCE -D_FILE_OFFSET_BITS=64

CXXFLAGS = -std=c++17 -pthread -g -O2 -W -Wall -iquote ../include -D_REENTRANT $(LARGE_FILE_FLAGS)
# CXXFLAGS = -std=c++11 -pthread -g -O2 -W -Wall -iquote ../include -D_REENTRANT $(LARGE_FILE_FLAGS)
# CXXFLAGS = -std=c++11 -pthread -g -O2 -W -Wall -iquote ../include -D_REENTRANT $(LARGE_FILE_FLAGS) -DDEBUG
## CXXFLAGS = -g -O2 -W -Wall -iquote ../include -D_REENTRANT $(LARGE_FILE_FLAGS)
# CXXFLAGS = -g -O2 -Wall -iquote ../include -D_REENTRANT -DSG_KERNEL_INCLUDES $(LARGE_FILE_FLAGS)
# CXXFLAGS = -g -O2 -Wall -pedantic -iquote ../include -D_REENTRANT $(LARGE_FILE_FLAGS)

LDFLAGS = -std=c++17 -pthread
# LDFLAGS = -std=c++11 -pthread
# LDFLAGS = -pthread

LIBFILESOLD = ../lib/sg_lib.o ../lib/sg_lib_data.o ../lib/sg_io_linux.o
LIBFILESNEW = ../lib/sg_pt_linux_nvme.o ../lib/sg_lib.o ../lib/sg_lib_data.o \
                ../lib/sg_pt_linux.o ../lib/sg_io_linux.o \
                ../lib/sg_pt_common.o  ../lib/sg_cmds_basic.o \
                ../lib/sg_cmds_basic2.o

all: $(EXECS)

extras: $(EXTRAS)


depend dep:
	for i in *.c; do $(CC) $(INCLUDES) $(CFLAGS) -M $$i; \
	done > .depend

clean:
	/bin/rm -f *.o $(EXECS) $(EXTRAS) $(BSG_EXTRAS) core .depend

sg_tst_excl: sg_tst_excl.o $(LIBFILESOLD)
	$(CXXLD) -o $@ $(LDFLAGS) $^

sg_tst_excl2: sg_tst_excl2.o $(LIBFILESNEW)
	$(CXXLD) -o $@ $(LDFLAGS) $^

sg_tst_excl3: sg_tst_excl3.o $(LIBFILESNEW)
	$(CXXLD) -o $@ $(LDFLAGS) $^

sg_tst_context: sg_tst_context.o $(LIBFILESNEW)
	$(CXXLD) -o $@ $(LDFLAGS) $^

sg_tst_async: sg_tst_async.o $(LIBFILESNEW)
	$(CXXLD) -o $@ $(LDFLAGS) $^

sgh_dd: sgh_dd.o $(LIBFILESNEW)
	$(CXXLD) -o $@ $(LDFLAGS) -pthread $^

install: $(EXECS)
	install -d $(INSTDIR)
	for name in $^; \
	 do install -s -o root -g root -m 755 $$name $(INSTDIR); \
	done
	install -d $(MANDIR)/$(MAN_PREF)
	for mp in $(MAN_PGS); \
	 do install -o root -g root -m 644 $$mp $(MANDIR)/$(MAN_PREF); \
	 gzip -9f $(MANDIR)/$(MAN_PREF)/$$mp; \
	done

uninstall:
	dists="$(EXECS)"; \
	for name in $$dists; do \
	 rm -f $(INSTDIR)/$$name; \
	done
	for mp in $(MAN_PGS); do \
	 rm -f $(MANDIR)/$(MAN_PREF)/$$mp.gz; \
	done

ifeq (.depend,$(wildcard .depend))
include .depend
endif
