.TH SCSI_TEMPERATURE "8" "May 2011" "sg3_utils\-1.36" SG3_UTILS
.SH NAME
scsi_temperature \- fetch the temperature of a SCSI device
.SH SYNOPSIS
.B scsi_temperature
[\fI\-\-help\fR] [\fI\-\-verbose\fR]
\fIDEVICE\fR [\fIDEVICE\fR]*
.SH DESCRIPTION
.\" Add any additional description here
.PP
This bash shell script calls the sg_logs utility on each given
\fIDEVICE\fR in order to find the device's temperature. The Temperature
log page is checked first and if it is not available then the Informational
Exceptions log page is checked.
.SH OPTIONS
Arguments to long options are mandatory for short options as well.
.TP
\fB\-h\fR, \fB\-\-help\fR
print out the usage message then exit.
.TP
\fB\-v\fR, \fB\-\-verbose\fR
increase level or verbosity.
.SH EXIT STATUS
The exit status of this script is 0 when it is successful. Otherwise the
exit status is that of the last sg_logs utility called. See
the sg3_utils(8) man page.
.SH AUTHORS
Written by D. Gilbert
.SH COPYRIGHT
Copyright \(co 2011\-2013 Douglas Gilbert
.br
This software is distributed under a FreeBSD license. There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
.SH "SEE ALSO"
.B sg_logs (sg3_utils)
